### ISSUE TITLE
Validation error on creating job

### ISSUE THREAD

**Issue by rokasmi** [Sylake/AkeneoProducerBundle#39]
I get locale validation error when trying to create a job. My locale is `en_US`, but `en_GB` and `de_de` are hardcoded in `Sylake\AkeneoProducerBundle\Connector\JobParameters\AkeneoProducer` (https://github.com/Sylake/AkeneoProducerBundle/blob/master/src/Connector/JobParameters/AkeneoProducer.php#L53). I think locales setting should be set from active system locales or made configurable

> $ app/console akeneo:batch:create-job "Sylake - Akeneo Producer" sylake_akeneo_producer export sylake_akeneo_producer
>
> A validation error occurred with the job configuration "
>   - Array[filters][structure][locales][0]:
>     The locale en_GB is not valid.
>   - Array[filters][structure][locales][1]:
>     The locale de_DE is not valid.".

**Comment by pamil** [comment]
@rokasmi are you willing to create a PR adding this configuration option?

**Comment by rokasmi** [comment]
Opened pull request, please review.
BTW, for the future, I think rabbitMQ configuration should be configurable too. What if I need multiple producers, so that different consumers could consume same changes

**Comment by pamil** [comment]
v1.0.0-beta.2 released with your PR. 🎉
